FROM public.ecr.aws/lambda/python:3.10

# Set the working directory within the container
WORKDIR /usr/src/app

# Copy the necessary files
COPY . .

COPY migration.sh ./migration.sh
COPY version.py ./version.py

# Copy the wait-for-it script
RUN chmod +x ./migration.sh

# Install dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Set PYTHONPATH
RUN export PYTHONPATH=${PYTHONPATH}:${PWD}

CMD ["pytest", "src/tests", "--vv", "--maxfail=1", "--disable-warnings"]
