version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  Build and Test:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install Dependencies
          command: |
            pip install virtualenv
            virtualenv env
            source env/bin/activate
            pip install -r requirements.txt
            echo 'export PYTHONPATH=$PYTHONPATH:$(pwd)' >> $BASH_ENV
      - run:
          name: Run Linting
          command: pylint /project
      - run:
          name: Run Linting
          command: pylint /project
      - run:
          name: Run Linting
          command: pylint /project
workflows:
  version: 2
  py_coin:
    jobs:
      - Build and Test