version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  Setup:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
            name: Run Linting
            command: pylint .
      - run:
            name: Run Type-Checks
            command: mypy .
      - run:
          name: Run Testing
          command: pytest .
    

workflows:
  version: 2
  py_coin:
    jobs:
      - Setup
      - Linting:
          requires:
            - Setup
      - Type-Checking:
          requires:
            - Setup
            - Linting
      - Testing:
          requires:
            - Setup
            - Linting
            - Type-Checking
