version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  Setup:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

  Pylint:
    steps:
      - run:
          name: Run Linitng
          command: pylint .

  Mypy:
    steps:
      - run:
          name: Run Mypy
          command: mypy .

  Pytest:
    steps:
      - run:
          name: Run tests
          command: pytest

workflows:
  sample: py_coin
    jobs:
      - Setup
      - Pylint
      - Mypy
      - Pytest
