version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  Build_and_Test:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
            export PYTHONPATH=$PYTHONPATH:$(pwd)
      - run:
          name: Run Linting
          command: |
            export PYTHONPATH=$PYTHONPATH:$(pwd)
            cp test.env .env
            pylint .
      - run:
          name: Run Type-Checks
          command: mypy .
      - run:
          name: Run Testing
          command: |
            export PYTHONPATH=$PYTHONPATH:$(pwd)
            pytest .

  Docker_Compose:
    docker:
      - image: docker/compose:1.29.2
    steps:
      - checkout

      # New steps to copy test.env to .env and source it
      - run:
          name: Copy test.env to .env
          command: cp test.env .env

      - run:
          name: Source .env file
          command: source .env

      - run:
          name: Run Docker-Compose
          command: docker-compose -f docker-compose.yaml up -d

workflows:
  version: 2
  py_coin:
    jobs:
      - Build_and_Test:
          requires:
            - Docker_Compose
