version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  Setup:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install Dependencies
          command: |
            pip install virtualenv
            virtualenv env
            source env/bin/activate
            pip install -r requirements.txt
            echo 'export PYTHONPATH=$PYTHONPATH:$(pwd)' >> $BASH_ENV

  Linting:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install Dependencies
          command: |
            pip install virtualenv
            virtualenv env
            source env/bin/activate
            pip install -r requirements.txt
            echo 'export PYTHONPATH=$PYTHONPATH:$(pwd)' >> $BASH_ENV
            pylint .

  Type-Checking:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install Dependencies
          command: |
            pip install virtualenv
            virtualenv env
            source env/bin/activate
            pip install -r requirements.txt
            echo 'export PYTHONPATH=$PYTHONPATH:$(pwd)' >> $BASH_ENV
            mypy .

  Testing:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install Dependencies
          command: |
            pip install virtualenv
            virtualenv env
            source env/bin/activate
            pip install -r requirements.txt
            echo 'export PYTHONPATH=$PYTHONPATH:$(pwd)' >> $BASH_ENV
            pytest .

workflows:
  version: 2
  py_coin:
    jobs:
      - Setup
      - Linting:
          requires:
            - Setup
      - Type-Checking:
          requires:
            - Setup
            - Linting
      - Testing:
          requires:
            - Setup
            - Linting
            - Type-Checking
