version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  Build_and_Test:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - run:
          name: Copy test.env to .env
          command: cp test.env .env

      - run:
          name: Source .env file
          command: source .env

      - run:
          name: Run Docker-Compose
          command: docker-compose up

      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
            export PYTHONPATH=$PYTHONPATH:$(pwd)

      - run:
          name: Run Linting
          command: |
            export PYTHONPATH=$PYTHONPATH:$(pwd)
            pylint .

      - run:
          name: Run Type-Checks
          command: mypy .

      - run:
          name: Run Testing
          command: |
            export PYTHONPATH=$PYTHONPATH:$(pwd)
            pytest .

      - run:
          name: Stop Docker-Compose
          command: docker-compose down

workflows:
  version: 2
  py_coin:
    jobs:
      - Build_and_Test
