version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  Build and Test:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
            export PYTHONPATH=$PYTHONPATH:$(pwd)
      - run:
            name: Run Linting
            command: |
              export PYTHONPATH=$PYTHONPATH:$(pwd)
              pylint .
      - run:
            name: Run Type-Checks
            command: mypy .
      - run:
          name: Run Testing
          command: pytest .
    

workflows:
  version: 2
  py_coin:
    jobs:
      - Build and Test