version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  Setup:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
            echo 'export PYTHONPATH=$PYTHONPATH:$(pwd)' >> $BASH_ENV
      - persist_to_workspace:
          root: /project
          paths:
            - .

  Linting:
    docker:
      - image: cimg/python:3.12

    steps:
      - attach_workspace:
          at: /project
      - run:
          name: Run Linting
          command: pylint /project

  Type-Checking:
    docker:
      - image: cimg/python:3.12

    steps:
      - attach_workspace:
          at: /project
      - run:
          name: Run Mypy
          command: mypy /project

  Testing:
    docker:
      - image: cimg/python:3.12

    steps:
      - attach_workspace:
          at: /project
      - run:
          name: Run tests
          command: pytest /project

workflows:
  version: 2
  py_coin:
    jobs:
      - Setup
      - Linting:
          requires:
            - Setup
      - Type-Checking:
          requires:
            - Setup
            - Linting
      - Testing:
          requires:
            - Setup
            - Linting
            - Type-Checking
